config/routes.rb
Rails.application.routes.draw do
  root to: "feedbacks#index"
  resources :feedbacks
  resources :regions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :region
  has_many :feedbacks
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :city

  validates :first_name, :last_name, :middle_name, presence: true
  validates :phone, format: { with:  /\A\(\d{3,5}\)\d{3,15}\z/i }
  validates :email, length: { in: 5..50 }
  validates :email, format: { with:  /\A[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}\z/i }
end

app/models/region.rb
class Region < ApplicationRecord
	has_many :cities

	validates :name, uniqueness: true

	scope :more_than, -> (number) { select(:id, :name, "COUNT(regions.id) as count").
		                            joins(cities: :feedbacks).
		                            group(:id).having('count(feedbacks.id) > ?', number) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: %i[ show edit update destroy ]

  # GET /feedbacks or /feedbacks.json
  def index
    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1 or /feedbacks/1.json
  def show
  end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit
  end

  # POST /feedbacks or /feedbacks.json
  def create
    @feedback = Feedback.new(feedback_params)

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to @feedback, notice: "Feedback was successfully created." }
        format.json { render :show, status: :created, location: @feedback }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feedbacks/1 or /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to @feedback, notice: "Feedback was successfully updated." }
        format.json { render :show, status: :ok, location: @feedback }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1 or /feedbacks/1.json
  def destroy
    @feedback.destroy
    respond_to do |format|
      format.html { redirect_to feedbacks_url, notice: "Feedback was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def feedback_params
      params.require(:feedback).permit(:first_name, :last_name, :middle_name, :city_id, :phone, :email, :comment)
    end
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
	before_action :set_region, only: %i[ show ] 

  # GET /feedbacks or /feedbacks.json
  def index
    @regions = Region.more_than(ENV["FEEDBACK_THRESHOLD"].to_i)
  end

  # GET /feedbacks/1 or /feedbacks/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_region
      @region = Region.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/feedbacks/_form.html.erb
<%= form_with(model: feedback) do |form| %>
  <% if feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
        <% feedback.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :middle_name %>
    <%= form.text_field :middle_name %>
  </div>

  <div class="field">
    <%= form.label :city_id %>
    <%= form.text_field :city_id %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing Feedback</h1>

<%= render 'form', feedback: @feedback %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feedbacks</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Middle name</th>
      <th>City</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feedbacks.each do |feedback| %>
      <tr>
        <td><%= feedback.first_name %></td>
        <td><%= feedback.last_name %></td>
        <td><%= feedback.middle_name %></td>
        <td><%= feedback.city.name %></td>
        <td><%= feedback.phone %></td>
        <td><%= feedback.email %></td>
        <td><%= feedback.comment %></td>
        <td><%= link_to 'Show', feedback %></td>
        <td><%= link_to 'Edit', edit_feedback_path(feedback) %></td>
        <td><%= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feedback', new_feedback_path %>
<%= link_to "Statistic", regions_path %>

app/views/feedbacks/new.html.erb
<h1>New Feedback</h1>

<%= render 'form', feedback: @feedback %>

<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @feedback.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @feedback.last_name %>
</p>

<p>
  <strong>Middle name:</strong>
  <%= @feedback.middle_name %>
</p>

<p>
  <strong>City:</strong>
  <%= @feedback.city_id %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @feedback.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @feedback.email %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @feedback.comment %>
</p>

<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Feedbacker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/regions/_table_header.html.erb
<thead>
  <tr>
    <th>№ <%= location %></th>
    <th>Наименование</th>
    <th>Количество комментариев</th>
  </tr>
</thead>

app/views/regions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Распределение по регионам</h1>

<table>
  <%= render 'table_header', location: 'региона' %>

  <tbody>
    <% @regions.each do |region| %>
      <tr>
        <td><%= region.id %></td>
        <td><%= link_to region.name, region %></td>
        <td><%= region.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/regions/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Распределение городам региона "<%= @region.name %>"</h1>

<table>
  <%= render 'table_header', location: 'города' %>

  <tbody>
    <% @region.cities.each do |city| %>
      <tr>
        <td><%= city.id %></td>
        <td><%= city.name %></td>
        <td><%= city.feedbacks.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>